### ISSUE TITLE
Recently update klantenvertellen.nl

### ISSUE THREAD

**Issue by senther** [Magmodules/magento1-kiyoh#1]
Recently the kiyoh.nl is changed to klantenvertellen.nl. Since then the score has not been updated anymore. Anyone any idea to solve this issue?

**Comment by Frank-Magmodules** [comment]
We have recently spoken with Klantvertellen.nl about the new API of KiyOh / klantenvertellen.nl. After internal consultation, we have decided to no longer adjust the extensions to their new API as *InterActivated* has already fulfilled this role as official extension provider for KiyOh / klantenvertellen.nl and Magento 1 runs towards the end as well.

Perhaps in the future we will change our minds and adjust the API or create an extension for Magento 2, but for this period and at the moment we are putting the extension on EOL (End Of Life) for Magento 1.

If you need us in the future, please contact us.
